import type { Candidate, Investigation, Source, StreamEvent } from './types';

export function dataUrl(path: string, staticDemo: boolean, baseUrl = '/'): string {
  if (!staticDemo) return path;
  const base = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
  if (path === '/api/dashboard') return `${base}demo/dashboard.json`;
  if (path.startsWith('/api/investigations/')) return `${base}demo/investigations/${path.slice('/api/investigations/'.length)}.json`;
  throw new Error('This action requires the local Astra research server.');
}

export function formatDate(value?: string | null, options?: Intl.DateTimeFormatOptions): string {
  if (!value) return 'Not disclosed';
  const date = new Date(value.length === 10 ? `${value}T12:00:00Z` : value);
  if (Number.isNaN(date.valueOf())) return value;
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC', ...options }).format(date);
}

export function safeSourceUrl(url: string): string | undefined {
  try {
    const parsed = new URL(url);
    return ['https:', 'http:'].includes(parsed.protocol) ? parsed.href : undefined;
  } catch {
    return undefined;
  }
}

export function investigationMarkdown(candidate: Candidate, investigation: Investigation, sources: Source[]): string {
  const combinedSources = new Map(sources.map((source) => [source.id, source]));
  for (const source of investigation.sources) combinedSources.set(source.id, source);
  const referencedIds = new Set([...candidate.sourceIds, ...investigation.findings.flatMap((finding) => finding.sourceIds), ...investigation.analogs.flatMap((analog) => analog.sourceIds)]);
  const sourceLine = (ids: string[]) => ids.length ? `Sources: ${ids.map((id) => {
    const source = combinedSources.get(id);
    return source && safeSourceUrl(source.url) ? `[${source.publisher} (${id})](${safeSourceUrl(source.url)})` : id;
  }).join('; ')}\n` : '';
  const lines = [
    `# ${candidate.drug}: Astra investigation`, '', candidate.indication, '',
    `- Sponsor: ${candidate.sponsor}`,
    `- Evidence as of: ${candidate.asOf}`,
    `- Reported FDA action target: ${formatDate(candidate.targetDate)} (not a promise of approval)`,
    `- Run: ${investigation.id}`,
    `- Model: ${investigation.model}`,
    `- Completed: ${investigation.createdAt}`,
    `- Provenance: ${investigation.provenance === 'recorded' ? 'Recorded Astra run' : 'Completed live Astra run'}`,
    `- Mode: ${investigation.mode}`, '',
    ...(investigation.question ? ['## Question', '', investigation.question, ''] : []),
    '## Outlook', '', investigation.outlook.verdict, '', investigation.summary, '',
    `**Timing assessment:** ${investigation.outlook.timing}`, '',
    investigation.outlook.probability === null ? '**Candidate-specific probability:** Not assigned.' : `**Astra probability estimate:** ${(investigation.outlook.probability * 100).toFixed(1)}%.`,
    investigation.outlook.probabilityBasis, '',
    '## Findings', '',
    ...investigation.findings.flatMap((finding, index) => [`### ${index + 1}. ${finding.title}`, '', `Evidence direction: ${finding.direction}`, '', finding.detail, '', sourceLine(finding.sourceIds), '']),
    ...(investigation.analogs.length ? ['## Historical comparisons', '', ...investigation.analogs.flatMap((analog) => [`### ${analog.title}`, '', analog.relevance, '', `**Key difference:** ${analog.difference}`, '', sourceLine(analog.sourceIds), ''])] : []),
    '## What to watch next', '', ...investigation.nextEvidence.map((item) => `- ${item}`), '',
    '## Scope and limitations', '', ...investigation.limitations.map((item) => `- ${item}`), '',
    '## Public sources', '', ...[...referencedIds].flatMap((id) => {
      const source = combinedSources.get(id);
      if (!source) return [`- ${id}: source metadata unavailable.`];
      return [`- **${source.title}** (${id}). ${source.publisher}. Published ${formatDate(source.publishedAt)}; retrieved ${formatDate(source.retrievedAt)}. ${safeSourceUrl(source.url) ?? 'Source URL unavailable.'}`];
    }), '',
    '---', '', 'Generated by FDAgent Approval Radar. Public-source research; not an FDA determination. Historical cohort rates are distinct from Astra’s candidate assessment.', '',
  ];
  return lines.join('\n');
}

/** Incrementally decode the response, including records split across UTF-8 chunks. */
export async function readInvestigationStream(response: Response, onEvent: (event: StreamEvent) => void): Promise<void> {
  if (!response.ok || response.headers.get('content-type')?.includes('application/json')) {
    const payload = await response.json().catch(() => null);
    throw new Error(payload?.error?.message ?? payload?.error ?? payload?.message ?? `Request failed (${response.status}).`);
  }
  if (!response.body) throw new Error('The server returned an empty investigation response.');
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let completed = false;
  const processLine = (line: string) => {
    if (!line.trim()) return;
    let event: StreamEvent;
    try { event = JSON.parse(line) as StreamEvent; }
    catch { throw new Error('The investigation returned an unreadable event. Please try again.'); }
    if (event.type === 'error') throw new Error(event.message);
    if (event.type === 'complete') completed = true;
    onEvent(event);
  };
  try {
    while (true) {
      const result = await reader.read();
      buffer += decoder.decode(result.value, { stream: !result.done });
      const lines = buffer.split('\n');
      buffer = lines.pop() ?? '';
      for (const line of lines) processLine(line);
      if (result.done) break;
    }
    processLine(buffer);
    if (!completed) throw new Error('The connection ended before the investigation completed. You can retry the investigation.');
  } finally {
    reader.releaseLock();
  }
}
